version: '3.8'

services:
  api:
    build: .
    container_name: orionjobs-api
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/orionjobs
      - ENVIRONMENT=development
      - COLLECT_MAX_PAGES=1
      - COLLECT_SLEEP_SECONDS=1
      - COLLECT_ADZUNA_MAX_REQUESTS=5
    volumes:
      - .:/app
    depends_on:
      - db
    restart: unless-stopped
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
  
  db:
    image: postgres:16
    container_name: orionjobs-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=orionjobs
    ports: 
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: