name: Run Tests

on:
  push:
    branches:
      - main
      - phase-3-data-collection
  pull_request:
    branches:
      - main
      - phase-3-data-collection

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Setup database with Alembic
      run: |
        export DATABASE_URL=sqlite:///test.db
        alembic upgrade head  # ✅ CRIAR TABELAS ANTES DOS TESTES

    - name: Run tests
      run: |
        export DATABASE_URL=sqlite:///test.db
        pytest